clockin/urls.py
from django.conf.urls import url
from django.contrib import admin
import moge_web.views

urlpatterns = [
    url(r'^$', moge_web.views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/', moge_web.views.logout),
    url(r'^login/', moge_web.views.login),
    url(r'^register/', moge_web.views.register),
    url(r'^display/(?P<list_id>[0-9]+)', moge_web.views.display),
    url(r'^display', moge_web.views.display),
]

moge_web/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from clockin import settings

# Create your models here.


class UserManager(BaseUserManager):
    def create_user(self, username, email, name, password):
        if not username:
            raise ValueError('Users must have an username')

        user = self.model(
            email=UserManager.normalize_email(email),
            username=username,
            name=name,
            is_admin=False,
            is_active=True
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password):
        email = 'admin@admin.com'
        name = 'admin'

        user = self.create_user(username, email, name, password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    id = models.AutoField(primary_key=True, unique=True)
    username = models.CharField(max_length=50, unique=True, db_index=True)
    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=50, db_index=True, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    @property
    def is_staff(self):
        return self.is_admin

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_absolute_url(self):
        return '/personal/%u' % self.pk


class List(models.Model):
    title = models.CharField(max_length=50, unique=True)
    time = models.DateTimeField(auto_now=False, auto_now_add=True)
    persons = models.ManyToManyField(User, blank=True)

moge_web/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404, JsonResponse, HttpResponseForbidden, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.views.decorators.http import require_http_methods
from django.contrib import auth
from moge_web.admin import UserCreationForm
from moge_web.models import *


# Create your views here.


def index(request):
    if not request.user.is_authenticated():
        return render(request, "login.html")
    current_lists = List.objects.order_by('-time')
    if len(current_lists) == 0:
        return render(request, "index.html")
    current_list = current_lists[0]
    is_in = request.user in current_list.persons.all()
    if request.method == 'POST':
        if is_in:
            current_list.persons.remove(request.user)
        else:
            current_list.persons.add(request.user)
        return HttpResponseRedirect('/')
    if request.user in current_list.persons.all():
        return render(request, "index.html", {'activity': current_list.title,
                                              'join': True})
    return render(request, "index.html", {'activity': current_list.title,
                                          'join': False})


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


def login(request, error_msg=""):
    if request.user.is_authenticated():
        return HttpResponseRedirect("/")
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect('/')
            else:
                return render(request, "login.html", {'error': "该用户已经被禁止登陆",
                                                      'username': username})
        else:
            return render(request, "login.html", {'error': "用户名或密码不正确",
                                                  'username': username})
    else:
        return render(request, "login.html", context=error_msg or {})


def register(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect("/")
    if request.method == 'POST':
        form = UserCreationForm(request.POST, request.FILES)
        if form.is_valid() and request.POST['password1'] and len(request.POST['password1']) >= 6:
            form.save()
            user = auth.authenticate(username=request.POST['username'], password=request.POST['password1'])
            auth.login(request, user)
            return HttpResponseRedirect("/")
        else:
            username = request.POST['username'] if request.POST['username'] else ""
            password1 = request.POST['password1'] if request.POST['password1'] else ""
            password2 = request.POST['password2'] if request.POST['password2'] else ""
            name = request.POST['name'] if request.POST['name'] else ""
            email = request.POST['email'] if request.POST['email'] else ""
            error_msg = "错误"
            if not username:
                error_msg = "请输入用户名"
            elif not (password1 and password2):
                error_msg = "请输入密码"
            elif not name:
                error_msg = "请输入昵称"
            elif not email:
                error_msg = "请输入邮箱"
            elif password1 != password2:
                error_msg = "两次密码不一致"
            elif len(password1) < 6:
                error_msg = "密码长度小于6位"
            elif User.objects.filter(username=username):
                error_msg = "用户名已经存在"
                username = ""
            elif User.objects.filter(email=email):
                error_msg = "邮箱已经注册"
                email = ""
            elif User.objects.filter(name=name):
                error_msg = "昵称已经被使用"
                name = ""
            return render(request, "register.html", {'error': error_msg,
                                                     'username': username,
                                                     'name': name,
                                                     'email': email})
    return render(request, "register.html")


@require_http_methods(["GET"])
def display(request, list_id=-1):
    if list_id == -1:
        lists = List.objects.all()
        res = []
        for x in lists:
            res.append({'id': x.id, 'title': x.title})
        return render(request, "display.html", {'title': "活动列表",
                                                 'num': len(res),
                                                 'list': res})
    mlist = List.objects.get(id=list_id)
    if not mlist:
        return HttpResponseRedirect('/display')
    res = []
    for x in mlist.persons.all():
        res.append(x.name)
    return render(request, "display.html", {'title': mlist.title + "参加人员",
                                             'num': len(res),
                                             'list': res})

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>运动打卡{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/styles/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/styles/base.css"/>
    {% block extracss %}{% endblock %}

</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="menu"><a href="/">首页</a></li>
                <li class="menu"><a href="/display">查看</a></li>
                {% if user.is_authenticated %}
                    <li class="menu"><a href="/logout">登出</a></li>
                    {% if user.is_admin %}
                    <li class="menu"><a href="/admin">管理</a></li>
                    {% endif %}
                {% else %}
                    <li class="menu"><a href="/login">登陆</a></li>
                    <li class="menu"><a href="/register">注册</a></li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
{% block footer %}
    <div class="footer">
        <p><span class="glyphicon glyphicon-heart"></span>Powered by YDY. OwO</p>
    </div>
{% endblock %}

<script src="/static/scripts/jquery.min.js"></script>
<script src="/static/scripts/bootstrap.min.js"></script>
{% block extrascripts %}{% endblock %}

</body>
</html>

templates/display.html
{% extends "base.html" %}

{% block title %}-列表{% endblock %}

{% block content %}
    <h3 class="center">{{ title }}</h3>
    <h4 class="center">共有{{ num }}项</h4>
    <ul>
    {% for x in list %}
        {% if x.id %}
            <li><a href="/display/{{ x.id }}">{{ x.title }}</a></li>
        {% else %}
            <li>{{ x }}</li>
        {% endif %}
    {% endfor %}
    </ul>
{% endblock %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="/static/styles/index.css"/>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated %}
        <h3 class="center">{{ user.name }}，你好！</h3>
        {% if activity %}
            {% if join %}
                <h3 class="center">你已经参加了{{ activity }}。</h3>
                <form class="center" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger m-btn" value="我没参加">
                </form>
            {% else %}
                <h3 class="center">你参加{{ activity }}了吗？</h3>
                <form class="center" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="submit" class="btn btn-success m-btn" value="参加了">
                </form>
            {% endif %}
        {% else %}
            <h3 class="center">当前并没有需要统计的活动。</h3>
        {% endif %}
    {% else %}
        <h3>请先登陆或者注册。</h3>
    {% endif %}
{% endblock %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="/static/styles/index.css"/>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}-用户登陆{% endblock %}

{% block content %}
    <div class="center">
        <div class="register_base panel panel-default ">
            <h2>用户登陆</h2>
            {% if error %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <strong>Error!</strong> {{ error }}
                </div>
            {% endif %}
            <div id="show-error"></div>
            <form class="form-base" onsubmit="return check(this)" action="/login/" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="m-row">
                    <label for="id_username">用户名:</label>
                    <input type="text" class="form-control" placeholder="Username" id="id_username" maxlength="50"
                           name="username" value="{{ username }}">
                </div>

                <div class="m-row">
                    <label for="id_password">密码:</label>
                    <input type="password" class="form-control" placeholder="不少于6个字符" id="id_password" name="password"
                           maxlength="128">
                </div>

                <input type="submit" class="btn btn-success m-btn" value="登陆">
            </form>
        </div>
    </div>
{% endblock %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="/static/styles/register.css"/>
{% endblock %}

{% block extrascripts %}
    <script src="/static/scripts/form-check.js"></script>
    <script>
        function check(thisform) {
            with (thisform) {
                if (validate_required(username, "请填写用户名") == false) {
                    username.focus();
                    return false
                }
                if (validate_required(password, "请填写密码") == false) {
                    password.focus();
                    return false
                }
                return true;
            }
        }
    </script>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}-用户注册{% endblock %}

{% block content %}
    <div class="center">
    <div class="register_base panel panel-default ">
        <h2>用户注册</h2>
        {% if error %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <strong>Error!</strong> {{ error }}
            </div>
        {% endif %}
        <div id="show-error"></div>
        <form class="form-base" onsubmit="return check(this)" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="m-row">
                <label for="id_username">用户名:</label>
                <input type="text" class="form-control" placeholder="Username" id="id_username" maxlength="50" name="username" value="{{ username }}">
            </div>

            <div class="m-row">
                <label for="id_password1">密码:</label>
                <input type="password" class="form-control" placeholder="不少于6个字符" id="id_password1" name="password1" maxlength="128">
            </div>

            <div class="m-row">
                <label for="id_password2">重复密码:</label>
                <input type="password" class="form-control" placeholder="不少于6个字符" id="id_password2" name="password2">
            </div>

            <div class="m-row">
                <label for="id_name">姓名:</label>
                <input type="text" class="form-control" placeholder="请填写真实姓名" id="id_name" maxlength="50" name="name" value="{{ name }}">
            </div>

            <div class="m-row">
                <label for="id_email">邮箱:</label>
                <input class="form-control" placeholder="email" id="id_email" maxlength="254" name="email" type="email" value="{{ email }}">
            </div>

            <input type="submit" class="btn btn-success m-btn" value="注册">
        </form>
    </div>
    </div>
{% endblock %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="/static/styles/register.css"/>
{% endblock %}

{% block extrascripts %}
    <script src="/static/scripts/form-check.js"></script>
    <script>
        function check(thisform) {
            with (thisform) {
                if (validate_required(username, "请填写用户名") == false) {
                    username.focus();
                    return false
                }
                if (check_password(password1) == false) {
                    password1.focus();
                    return false
                }
                if (check_password(password2) == false) {
                    password2.focus();
                    return false
                }
                if (validate_required(name, "请填写昵称") == false) {
                    name.focus();
                    return false
                }
                if (validate_required(email, "请填写邮箱") == false) {
                    email.focus();
                    return false
                }
                if (validate_required(describe, "请填写自我描述") == false) {
                    describe.focus();
                    return false
                }
                return true;
            }
        }
    </script>
{% endblock %}